/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DEDROX (https://sketchfab.com/Raghavprasanna)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/hopper-car-e8dc119154e448c987674f4119f4b75c
title: Hopper car
*/

import React, {useRef} from 'react';
import {useGLTF, useAnimations} from '@react-three/drei';
import {motion} from 'framer-motion-3d';

export function HopperCar(props) {
  const group = useRef();
  const {nodes, materials, animations} = useGLTF('/hopper_car.glb');
  const {actions} = useAnimations(animations, group);
  const {isOpen} = props;
  console.log('action', actions, animations[0]);

  const variants = {
    open: {rotateZ: (-30 * Math.PI) / 180, x: 0, y: 0, z: 0},
    closed: {rotateZ: (60 * Math.PI) / 180, x:2.5, y: 2.5, z: 2.5},
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <motion.group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          initial={'closed'}
          animate={isOpen ? 'open' : 'closed'}
          transition={{
            delay: 0.5,
            duration: 1,
          }}
          variants={variants}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group
                name='Traim_0'
                position={[-6.98, 3.79, -0.62]}
                rotation={[0, 1.53, 0]}>
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder019_22'
                position={[5.78, 5.78, 5.81]}
                scale={[0.8, 0.63, 0.8]}>
                <mesh
                  name='Object_46'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder017_24'
                position={[3.75, 5.78, 5.81]}
                scale={[0.8, 0.63, 0.8]}>
                <mesh
                  name='Object_50'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='R3-17_1'
                position={[6.51, 0.69, -0.38]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.75}>
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials['R3-17']}
                />
              </group>
              <group name='Plane015_2' position={[3.48, 5.68, -2.66]}>
                <mesh
                  name='Object_8'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane014_3' position={[3.04, -0.03, 5.1]}>
                <mesh
                  name='Object_10'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane013_4' position={[3.04, -0.03, 5.1]}>
                <mesh
                  name='Object_12'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane012_5' position={[2.32, 7.73, -3.16]}>
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Plane010_6'
                position={[3.04, -0.03, 5.1]}
                scale={3.06}>
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane008_8'>
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane004_9' position={[0, 4.83, 0]} scale={7}>
                <mesh
                  name='Object_20'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name='Plane003_10'>
                <mesh
                  name='Object_22'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane002_11'>
                <mesh
                  name='Object_24'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Plane_12'>
                <mesh
                  name='Object_26'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='D9-13dP_13'
                position={[0.11, 4.92, 5.07]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={0.93}>
                <mesh
                  name='Object_28'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials['D9-13dP']}
                />
              </group>
              <group
                name='Cylinder027_14'
                position={[4.52, 2.68, 2.4]}
                scale={0.22}>
                <mesh
                  name='Object_30'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder026_15'
                position={[4.52, 2.68, 2.4]}
                scale={0.22}>
                <mesh
                  name='Object_32'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder025_16'
                position={[-7.21, 0.09, 7.5]}
                rotation={[0, -1.05, 0]}
                scale={0.08}>
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder024_17'
                position={[-7.26, 0.09, 8.08]}
                rotation={[0, -1.05, 0]}
                scale={0.1}>
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.Master}
                />
              </group>

              {/* doll */}
              <group
                name='Cylinder023_18'
                position={[-7.03, 0.21, 8.38]}
                rotation={[0, -1.05, 0]}
                scale={0.22}>
                <mesh
                  name='Object_38'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.Master}
                />
              </group>

              <group
                name='Cylinder022_19'
                position={[1.68, 0.12, 7.35]}
                scale={0.1}>
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder021_20'
                position={[1.49, 8.53, -3.37]}
                rotation={[0, Math.PI / 4, 0]}>
                <mesh
                  name='Object_42'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder020_21'
                position={[2.36, 8.8, -3.37]}
                rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                  name='Object_44'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder018_23'
                position={[5.78, 5.78, 5.81]}
                scale={[0.8, 0.63, 0.8]}>
                <mesh
                  name='Object_48'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder016_25'
                position={[3.75, 5.78, 5.81]}
                scale={[0.8, 0.63, 0.8]}>
                <mesh
                  name='Object_52'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder015_26'
                position={[2.36, 8.53, -4.29]}
                rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
                <mesh
                  name='Object_54'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Cylinder014_27' position={[1.49, 8.53, -4.29]}>
                <mesh
                  name='Object_56'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder013_28'
                position={[2.19, 0.21, 7.3]}
                scale={0.22}>
                <mesh
                  name='Object_58'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder012_29'
                position={[1.72, 2.73, 3.67]}
                scale={0.22}>
                <mesh
                  name='Object_60'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder011_30'
                position={[0, 6.12, 2.35]}
                scale={[1, 1.45, 1]}>
                <mesh
                  name='Object_62'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder010_31'
                position={[7.24, 0.21, 3.44]}
                scale={0.22}>
                <mesh
                  name='Object_64'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder009_32'
                position={[7.32, 0.14, -2.26]}
                rotation={[-0.15, -0.02, -0.13]}
                scale={0.1}>
                <mesh
                  name='Object_66'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder008_33'
                position={[6.97, 0.2, -2.58]}
                rotation={[0.18, 0.05, 0.16]}
                scale={0.1}>
                <mesh
                  name='Object_68'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder007_34'
                position={[5.65, -2.3, 1.54]}
                scale={0.22}>
                <mesh
                  name='Object_70'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name='Cylinder006_35'
                position={[-5.9, 0.21, 5.61]}
                scale={0.22}>
                <mesh
                  name='Object_72'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder005_36'
                position={[6.81, 0.81, -2.21]}
                rotation={[-0.41, -0.12, -0.01]}
                scale={0.1}>
                <mesh
                  name='Object_74'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder004_37'
                position={[-7.41, 0.35, -2.27]}
                scale={0.22}>
                <mesh
                  name='Object_76'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder003_38'
                position={[6.82, 0.12, -2.11]}
                scale={0.1}>
                <mesh
                  name='Object_78'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder002_39'
                position={[0.93, 0.35, -5.87]}
                scale={0.22}>
                <mesh
                  name='Object_80'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cylinder001_40'
                position={[1.44, 0.35, -5.57]}
                scale={0.22}>
                <mesh
                  name='Object_82'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cube010_41'
                position={[6.86, 1.67, 2.23]}
                scale={0.08}>
                <mesh
                  name='Object_84'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cube005_42'
                position={[-0.17, -0.17, -3.51]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.6}>
                <mesh
                  name='Object_86'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials['Material.018']}
                />
                <mesh
                  name='Object_87'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_87.geometry}
                  material={materials.Stop_sign_dark_red}
                />
              </group>
              <group
                name='Cube004_43'
                position={[-3.81, 2.54, -0.72]}
                scale={0.07}>
                <mesh
                  name='Object_89'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_89.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Cube003_44' position={[-5.47, 1.43, -4.93]}>
                <mesh
                  name='Object_92'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={materials.material_0}
                />
                <mesh
                  name='Object_91'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='Cube002_45'
                position={[5.36, 2.33, 2.85]}
                rotation={[0, 0.93, 0]}
                scale={0.02}>
                <mesh
                  name='Object_95'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_95.geometry}
                  material={materials['CW12-1']}
                />
                <mesh
                  name='Object_94'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Master}
                />
              </group>
              <group name='Cube_46' position={[-6, 0.93, 2.56]} scale={0.17}>
                <mesh
                  name='Object_97'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_97.geometry}
                  material={materials.material_0}
                />
              </group>
              <group
                name='BezierCurve005_47'
                position={[-1.74, 4.19, 1.36]}
                scale={0.46}>
                <mesh
                  name='Object_99'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_99.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='BezierCurve004_48'
                position={[-4.66, 4.19, 1.36]}
                scale={0.46}>
                <mesh
                  name='Object_101'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_101.geometry}
                  material={materials.Master}
                />
              </group>
              <group
                name='BezierCurve002_49'
                position={[4.76, 3.25, 6.88]}
                rotation={[0, Math.PI / 2, 0]}
                scale={0.51}>
                <mesh
                  name='Object_103'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_103.geometry}
                  material={materials.Master}
                />
              </group>
            </group>
          </group>
        </motion.group>
      </group>
    </group>
  );
}

useGLTF.preload('/hopper_car.glb');
