/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AirStudios (https://sketchfab.com/sebbe613)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-5f9c35be31a047928eace8b415a8ee3a
title: Earth
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from 'framer-motion-3d';
import { useFrame } from '@react-three/fiber'

const variants = {
  day: {rotateZ: (-30 * Math.PI) / 180, x: 0, y: 0, z: 0},
  night: {rotateZ: (90 * Math.PI) / 180, x:2.5, y: 10, z: 10},
};

export function EarthModel({dayLight, ...props}) {
  const { nodes, materials } = useGLTF("/earth.glb");
  const myGlobe = React.useRef()

  useFrame(({ clock }) => {
    const second = clock.getElapsedTime() / 50;
    myGlobe.current.rotation.x = second;
    myGlobe.current.rotation.z = second;
    myGlobe.current.rotation.y = second;
  })

  return (
    <motion.group ref={myGlobe} {...props} dispose={null}
          initial={dayLight ? 'day' : 'night'}
          animate={dayLight ? 'night' : 'day'}
          transition={{
            delay: 0.2,
            duration: 5,
          }}
          variants={variants}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={96.72}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere1_phong1_0.geometry}
              material={materials.phong1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere1_phong1_0_1.geometry}
              material={materials.phong1}
            />
          </group>
          <group scale={97.46}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere4_lambert6_0.geometry}
              material={materials.lambert6}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere4_lambert6_0_1.geometry}
              material={materials.lambert6}
            />
          </group>
          <group scale={98.1}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere5_lambert7_0.geometry}
              material={materials.lambert7}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere5_lambert7_0_1.geometry}
              material={materials.lambert7}
            />
          </group>
        </group>
      </group>
    </motion.group>
  );
}

useGLTF.preload("/earth.glb");
